import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedLargeFABWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedNavigationbarWidget7.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedFrame8Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedFrame9Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedSearchBarWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedDeviceDeviceframecomponentsWidget15.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedLine24Widget9.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedDeviceDeviceframecomponentsWidget14.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedRecentSearchesWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchwidget8/generated/GeneratedTopappbarWidget7.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget7(),
              ),
              Positioned(
                left: 12.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 45.0,
                child: GeneratedSearchBarWidget(),
              ),
              Positioned(
                left: -4.547473508864641e-13,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget15(),
              ),
              Positioned(
                left: 12.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 30.0,
                child: GeneratedRecentSearchesWidget(),
              ),
              Positioned(
                left: 300.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedLargeFABWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 50.0,
                child: GeneratedFrame8Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 50.0,
                child: GeneratedFrame9Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 50.0,
                child: GeneratedFrame8Widget1(),
              ),
              Positioned(
                left: -1.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 414.0193176269531,
                height: 0.5,
                child: GeneratedLine24Widget9(),
              )
            ]),
      ),
    ));
  }
}
