import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedsettingsemptywidget/generated/GeneratedCOMINGSOONWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedsettingsemptywidget/generated/GeneratedDeviceDeviceframecomponentsWidget25.dart';
import 'package:flutterapp/food_20rootsapp/generatedsettingsemptywidget/generated/GeneratedTopappbarWidget11.dart';
import 'package:flutterapp/food_20rootsapp/generatedsettingsemptywidget/generated/GeneratedNavigationbarWidget11.dart';
import 'package:flutterapp/food_20rootsapp/generatedsettingsemptywidget/generated/GeneratedDeviceDeviceframecomponentsWidget24.dart';

/* Frame Settings Empty
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsEmptyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget24(),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget25(),
              ),
              Positioned(
                left: 82.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 44.0,
                child: GeneratedCOMINGSOONWidget(),
              )
            ]),
      ),
    ));
  }
}
