import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup17widget2/generated/GeneratedStackedcardWidget23.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup17widget2/generated/GeneratedStackedcardWidget17.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup17widget2/generated/GeneratedStackedcardWidget18.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup17widget2/generated/GeneratedStackedcardWidget22.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup17widget2/generated/GeneratedStackedcardWidget21.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup17widget2/generated/GeneratedStackedcardWidget20.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup17widget2/generated/GeneratedStackedcardWidget16.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup17widget2/generated/GeneratedStackedcardWidget19.dart';

/* Group Group 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup17Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 383.0,
      height: 794.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 1.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget16(),
            ),
            Positioned(
              left: 1.0,
              top: 202.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget17(),
            ),
            Positioned(
              left: 198.0,
              top: 404.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget18(),
            ),
            Positioned(
              left: 0.0,
              top: 404.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget19(),
            ),
            Positioned(
              left: 198.0,
              top: 202.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget20(),
            ),
            Positioned(
              left: 0.0,
              top: 606.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget21(),
            ),
            Positioned(
              left: 195.0,
              top: 606.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget22(),
            ),
            Positioned(
              left: 198.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget23(),
            )
          ]),
    ));
  }
}
