import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedButtonWidget134.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedDeviceDeviceframecomponentsWidget35.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedJadaWidget.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedHeaderWidget130.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedLine25Widget.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedDataMobileGraphWidget.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedHeaderWidget131.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedLine24Widget31.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedNavigationbarWidget16.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedButtonWidget133.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedButtonWidget135.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedDeviceDeviceframecomponentsWidget34.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedTopappbarWidget16.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedHeaderWidget128.dart';
import 'package:flutterapp/food_20rootsapp/generateduserwidget/generated/GeneratedHeaderWidget129.dart';

/* Frame User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget34(),
              ),
              Positioned(
                left: 69.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 40.0,
                child: GeneratedButtonWidget133(),
              ),
              Positioned(
                left: 177.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 40.0,
                child: GeneratedButtonWidget134(),
              ),
              Positioned(
                left: 257.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 40.0,
                child: GeneratedButtonWidget135(),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget16(),
              ),
              Positioned(
                left: null,
                top: 141.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 120.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 179.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 33.0,
                child: GeneratedJadaWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 231.0,
                child: GeneratedDataMobileGraphWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 348.0,
                right: 0.0,
                bottom: 529.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9223300970873787;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.03640776699029126,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedGroup5Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 447.0,
                right: 0.0,
                bottom: 430.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9271844660194175;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.03640776699029126,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedGroup3Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 398.0,
                right: 0.0,
                bottom: 479.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9247572815533981;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.03640776699029126,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedGroup4Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget35(),
              ),
              Positioned(
                left: 0.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 414.0193176269531,
                height: 0.5,
                child: GeneratedLine24Widget31(),
              ),
              Positioned(
                left: 0.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 414.0193176269531,
                height: 0.5,
                child: GeneratedLine25Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 30.0,
                child: GeneratedHeaderWidget128(),
              ),
              Positioned(
                left: 15.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 26.0,
                child: GeneratedHeaderWidget129(),
              ),
              Positioned(
                left: 15.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 26.0,
                child: GeneratedHeaderWidget130(),
              ),
              Positioned(
                left: 179.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 29.0,
                child: GeneratedHeaderWidget131(),
              )
            ]),
      ),
    ));
  }
}
