import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedstorewidget/generated/GeneratedNavigationbarWidget20.dart';
import 'package:flutterapp/food_20rootsapp/generatedstorewidget/generated/GeneratedLine24Widget40.dart';
import 'package:flutterapp/food_20rootsapp/generatedstorewidget/generated/GeneratedTopappbarWidget20.dart';
import 'package:flutterapp/food_20rootsapp/generatedstorewidget/generated/GeneratedDeviceDeviceframecomponentsWidget42.dart';
import 'package:flutterapp/food_20rootsapp/generatedstorewidget/generated/GeneratedDeviceDeviceframecomponentsWidget43.dart';
import 'package:flutterapp/food_20rootsapp/generatedstorewidget/generated/GeneratedHeadWidget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedstorewidget/generated/GeneratedImage17Widget.dart';

/* Frame Store
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStoreWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget20(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget42(),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget20(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget43(),
              ),
              Positioned(
                left: 0.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 414.0193786621094,
                height: 137.0,
                child: GeneratedHeadWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 414.0193176269531,
                height: 0.5,
                child: GeneratedLine24Widget40(),
              ),
              Positioned(
                left: -2.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 546.0,
                child: GeneratedImage17Widget(),
              )
            ]),
      ),
    ));
  }
}
