import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedfirstlevelwidget1/generated/GeneratedCoverWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedfirstlevelwidget1/generated/GeneratedDarkWidget6.dart';
import 'package:flutterapp/food_20rootsapp/generatedfirstlevelwidget1/generated/GeneratedDarkWidget4.dart';
import 'package:flutterapp/food_20rootsapp/generatedfirstlevelwidget1/generated/GeneratedLightHamburgerWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedfirstlevelwidget1/generated/GeneratedFirstLevelDefaultWidget4.dart';
import 'package:flutterapp/food_20rootsapp/generatedfirstlevelwidget1/generated/GeneratedFirstLevelDefaultWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/food_20rootsapp/generatedfirstlevelwidget1/generated/GeneratedFirstLevelDefaultWidget6.dart';
import 'package:flutterapp/food_20rootsapp/generatedfirstlevelwidget1/generated/GeneratedDialogWidget1.dart';

/* Frame First Level
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFirstLevelWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(0.0),
        topRight: Radius.circular(0.0),
        bottomRight: Radius.circular(20.0),
        bottomLeft: Radius.circular(20.0),
      ),
      child: Container(
        width: 412.0,
        height: 302.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(0.0),
            topRight: Radius.circular(0.0),
            bottomRight: Radius.circular(20.0),
            bottomLeft: Radius.circular(20.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(0.0),
                  topRight: Radius.circular(0.0),
                  bottomRight: Radius.circular(20.0),
                  bottomLeft: Radius.circular(20.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 1.6507354130018626;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * -0.6507352614244878,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDialogWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 56.0,
                child: GeneratedLightHamburgerWidget1(),
              ),
              Positioned(
                left: 8.0,
                top: 56.0,
                right: 8.0,
                bottom: null,
                width: null,
                height: 48.0,
                child: GeneratedFirstLevelDefaultWidget4(),
              ),
              Positioned(
                left: 8.0,
                top: 104.0,
                right: 8.0,
                bottom: null,
                width: null,
                height: 48.0,
                child: GeneratedFirstLevelDefaultWidget5(),
              ),
              Positioned(
                left: 8.0,
                top: 152.0,
                right: 8.0,
                bottom: null,
                width: null,
                height: 48.0,
                child: GeneratedFirstLevelDefaultWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: 72.0,
                child: GeneratedCoverWidget1(),
              ),
              Positioned(
                left: 112.0,
                top: null,
                right: 16.0,
                bottom: 23.0,
                width: null,
                height: 40.0,
                child: GeneratedDarkWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: 23.0,
                width: 80.0,
                height: 40.0,
                child: GeneratedDarkWidget6(),
              )
            ]),
      ),
    ));
  }
}
