import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup9widget/generated/GeneratedStackedcardWidget29.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup9widget/generated/GeneratedStackedcardWidget36.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup9widget/generated/GeneratedStackedcardWidget33.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup9widget/generated/GeneratedStackedcardWidget34.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup9widget/generated/GeneratedStackedcardWidget32.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup9widget/generated/GeneratedStackedcardWidget35.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup9widget/generated/GeneratedStackedcardWidget31.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup9widget/generated/GeneratedStackedcardWidget30.dart';

/* Group Group 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 383.0,
      height: 794.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 1.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget29(),
            ),
            Positioned(
              left: 1.0,
              top: 202.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget30(),
            ),
            Positioned(
              left: 198.0,
              top: 404.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget31(),
            ),
            Positioned(
              left: 0.0,
              top: 404.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget32(),
            ),
            Positioned(
              left: 198.0,
              top: 202.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget33(),
            ),
            Positioned(
              left: 0.0,
              top: 606.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget34(),
            ),
            Positioned(
              left: 195.0,
              top: 606.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget35(),
            ),
            Positioned(
              left: 198.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 185.0,
              height: 188.0,
              child: GeneratedStackedcardWidget36(),
            )
          ]),
    ));
  }
}
