import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedAreEletricCarsReallyMoreEnvironmentallyFriendlyWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle272Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle274Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/Generated10EcoFriendlyBuildingMaterialWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle270Widget2.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedSevenBillionDreamsOnePlanetConsumewithCareWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedHowHydrogenCouldSolvetheEnergyCrisisWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedSustainabilityineverydaylifeWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedClimateChangeAShortFilmWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle271Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedWhichCountriesAreTheMostEcoFriendlyWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedPlasticpollutionWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle267Widget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle250Widget5.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle269Widget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle268Widget4.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedUpcyclingandRecyclingHacksWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle273Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedRectangle275Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget2/generated/GeneratedOneEarthEnvironmentalFilmWidget1.dart';

/* Frame Videos scroll
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVideosscrollWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 904.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 904.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.022123893805309734,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle250Widget5(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.022123893805309734,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle267Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.03982300884955752;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.15597345132743362,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedOneEarthEnvironmentalFilmWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.03982300884955752;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.15597345132743362,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedClimateChangeAShortFilmWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.2079646017699115,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle268Widget4(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.2079646017699115,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle269Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.03982300884955752;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.3418141592920354,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedUpcyclingandRecyclingHacksWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.03982300884955752;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.34513274336283184,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            Generated10EcoFriendlyBuildingMaterialWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.8008849557522124,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle274Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.8008849557522124,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle275Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.0586283185840708;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.9347345132743363,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedAreEletricCarsReallyMoreEnvironmentallyFriendlyWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.03982300884955752;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.9380530973451328,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedHowHydrogenCouldSolvetheEnergyCrisisWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.6084070796460177,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle272Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.6084070796460177,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle273Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.02101769911504425;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.7555309734513275,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedPlasticpollutionWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.03982300884955752;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.745575221238938,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedWhichCountriesAreTheMostEcoFriendlyWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.3971238938053097,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle270Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4666666666666667;

                                final double height =
                                    constraints.maxHeight * 0.12831858407079647;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.3971238938053097,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle271Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.03982300884955752;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.022222222222222223,
                                      y: constraints.maxHeight *
                                          0.543141592920354,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedSustainabilityineverydaylifeWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.4722222222222222;

                                final double height =
                                    constraints.maxHeight * 0.0586283185840708;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5111111111111111,
                                      y: constraints.maxHeight *
                                          0.5342920353982301,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedSevenBillionDreamsOnePlanetConsumewithCareWidget1(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
