import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedframe2608133widget/generated/GeneratedRectangle278Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedframe2608133widget/generated/GeneratedGroup17Widget1.dart';

/* Frame Frame 2608133
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2608133Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 826.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 412.0,
                      height: 826.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 412.0,
                              height: 826.0,
                              child: GeneratedRectangle278Widget1(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 383.0,
                              height: 794.0,
                              child: GeneratedGroup17Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
