import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget1/generated/GeneratedNavigationbarWidget5.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget1/generated/GeneratedDeviceDeviceframecomponentsWidget10.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget1/generated/GeneratedButtonWidget63.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget1/generated/GeneratedItemWidget6.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget1/generated/GeneratedButtonWidget62.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget1/generated/GeneratedButtonWidget64.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget1/generated/GeneratedTopappbarWidget5.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget1/generated/GeneratedDeviceDeviceframecomponentsWidget11.dart';

/* Frame Favorites Products
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFavoritesProductsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget5(),
              ),
              Positioned(
                left: -4.547473508864641e-13,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget11(),
              ),
              Positioned(
                left: 53.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 40.0,
                child: GeneratedButtonWidget62(),
              ),
              Positioned(
                left: 165.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 40.0,
                child: GeneratedButtonWidget63(),
              ),
              Positioned(
                left: 270.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 40.0,
                child: GeneratedButtonWidget64(),
              ),
              Positioned(
                left: -6.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 414.0000305175781,
                height: 90.0,
                child: GeneratedItemWidget6(),
              )
            ]),
      ),
    ));
  }
}
