import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedItemWidget5.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedButtonWidget61.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedLine24Widget4.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedButtonWidget60.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedButtonWidget59.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedItemWidget4.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedDeviceDeviceframecomponentsWidget8.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedItemWidget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedTopappbarWidget4.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedDeviceDeviceframecomponentsWidget9.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesproductswidget/generated/GeneratedNavigationbarWidget4.dart';

/* Frame Favorites Products
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFavoritesProductsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget4(),
              ),
              Positioned(
                left: -4.547473508864641e-13,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget9(),
              ),
              Positioned(
                left: 53.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 40.0,
                child: GeneratedButtonWidget59(),
              ),
              Positioned(
                left: 165.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 40.0,
                child: GeneratedButtonWidget60(),
              ),
              Positioned(
                left: 270.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 40.0,
                child: GeneratedButtonWidget61(),
              ),
              Positioned(
                left: -6.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 419.0,
                height: 90.0,
                child: GeneratedItemWidget3(),
              ),
              Positioned(
                left: -3.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 414.0000305175781,
                height: 90.0,
                child: GeneratedItemWidget4(),
              ),
              Positioned(
                left: -2.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 414.0193176269531,
                height: 0.5,
                child: GeneratedLine24Widget4(),
              ),
              Positioned(
                left: -3.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 422.0,
                height: 90.0,
                child: GeneratedItemWidget5(),
              )
            ]),
      ),
    ));
  }
}
