import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailswidget/generated/GeneratedFrame2608139Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailswidget/generated/GeneratedExtendedFABWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailswidget/generated/GeneratedDeviceDeviceframecomponentsWidget2.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailswidget/generated/GeneratedDeviceDeviceframecomponentsWidget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailswidget/generated/GeneratedTopappbarWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailswidget/generated/GeneratedNavigationbarWidget1.dart';

/* Frame Recipe Details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRecipeDetailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 703.0,
                child: GeneratedFrame2608139Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget3(),
              ),
              Positioned(
                left: 205.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 56.0,
                child: GeneratedExtendedFABWidget(),
              )
            ]),
      ),
    ));
  }
}
