import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesrecipeswidget/generated/GeneratedButtonWidget66.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesrecipeswidget/generated/GeneratedButtonWidget67.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesrecipeswidget/generated/GeneratedTopappbarWidget6.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesrecipeswidget/generated/GeneratedStackedcardWidget28.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesrecipeswidget/generated/GeneratedDeviceDeviceframecomponentsWidget13.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesrecipeswidget/generated/GeneratedButtonWidget65.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesrecipeswidget/generated/GeneratedDeviceDeviceframecomponentsWidget12.dart';
import 'package:flutterapp/food_20rootsapp/generatedfavoritesrecipeswidget/generated/GeneratedNavigationbarWidget6.dart';

/* Frame Favorites Recipes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFavoritesRecipesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget6(),
              ),
              Positioned(
                left: -4.547473508864641e-13,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget13(),
              ),
              Positioned(
                left: 53.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 40.0,
                child: GeneratedButtonWidget65(),
              ),
              Positioned(
                left: 165.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 40.0,
                child: GeneratedButtonWidget66(),
              ),
              Positioned(
                left: 270.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 40.0,
                child: GeneratedButtonWidget67(),
              ),
              Positioned(
                left: 17.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 188.0,
                child: GeneratedStackedcardWidget28(),
              )
            ]),
      ),
    ));
  }
}
