import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedlisteditionwidget/generated/GeneratedDeviceDeviceframecomponentsWidget22.dart';
import 'package:flutterapp/food_20rootsapp/generatedlisteditionwidget/generated/GeneratedTopappbarWidget10.dart';
import 'package:flutterapp/food_20rootsapp/generatedlisteditionwidget/generated/GeneratedItemWidget24.dart';
import 'package:flutterapp/food_20rootsapp/generatedlisteditionwidget/generated/GeneratedDeviceDeviceframecomponentsWidget23.dart';
import 'package:flutterapp/food_20rootsapp/generatedlisteditionwidget/generated/GeneratedNavigationbarWidget10.dart';
import 'package:flutterapp/food_20rootsapp/generatedlisteditionwidget/generated/GeneratedItemWidget23.dart';
import 'package:flutterapp/food_20rootsapp/generatedlisteditionwidget/generated/GeneratedItemWidget25.dart';

/* Frame List Edition
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListEditionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget22(),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget23(),
              ),
              Positioned(
                left: -2.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 423.0,
                height: 83.0,
                child: GeneratedItemWidget23(),
              ),
              Positioned(
                left: -2.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 84.0,
                child: GeneratedItemWidget24(),
              ),
              Positioned(
                left: -1.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 82.0,
                child: GeneratedItemWidget25(),
              )
            ]),
      ),
    ));
  }
}
