import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedStudyConfirmsThatGabonIstheLargestStrongholdforCritical.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedBiotechnologycouldprovideanenvironmentallymoresustainab.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedLivingWallsCanReduceHeatLostfromBuildingsbyOver30Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedRectangle259Widget2.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedRectangle250Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedRectangle266Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedRectangle262Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedResearchPushesAutoIndustryClosertoCleanCarsPoweredbyDir.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedRectangle261Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/Generated30magoWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedShapingaSustainableFutureforaCommonPlasticWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/Generated2hagoWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedSizingUptheChallengesinExtractingLithiumfromGeothermalB.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/Generated4hagoWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/Generated2dagoWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/Generated8hagoWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/Generated1dagoWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/Generated1hagoWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/Generated45magoWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedFreeGreenServicesCouldSubstantiallyReduceEmissionsWidge.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedHowSugarLovingMicrobesCouldHelpPowerFutureCarsWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/Generated8magoWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedRectangle260Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedRectangle265Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedRectangle263Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedRectangle264Widget5.dart';
import 'package:flutterapp/food_20rootsapp/generatednewsscrollwidget/generated/GeneratedHealthierUKDietsLinkedtoLowerGreenhouseGasEmissionsWidg.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame News scroll
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewsscrollWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 957.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 957.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24444444444444444;

                                final double height =
                                    constraints.maxHeight * 0.09195402298850575;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03888888888888889,
                                      y: constraints.maxHeight *
                                          0.02089864158829676,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle250Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6583333333333333;

                                final double height =
                                    constraints.maxHeight * 0.07314524555903866;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.02089864158829676,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedBiotechnologycouldprovideanenvironmentallymoresustainab(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.14444444444444443;

                                final double height = constraints.maxHeight *
                                    0.019853709508881923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.09508881922675026,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated8magoWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24444444444444444;

                                final double height =
                                    constraints.maxHeight * 0.09195402298850575;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.12957157784743992,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle259Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6583333333333333;

                                final double height = constraints.maxHeight *
                                    0.055381400208986416;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.14315569487983282,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedResearchPushesAutoIndustryClosertoCleanCarsPoweredbyDir(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16944444444444445;

                                final double height = constraints.maxHeight *
                                    0.019853709508881923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.20376175548589343,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated30magoWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24444444444444444;

                                final double height =
                                    constraints.maxHeight * 0.09195402298850575;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03611111111111111,
                                      y: constraints.maxHeight *
                                          0.23824451410658307,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle260Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6583333333333333;

                                final double height = constraints.maxHeight *
                                    0.055381400208986416;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3111111111111111,
                                      y: constraints.maxHeight *
                                          0.25182863113897597,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedSizingUptheChallengesinExtractingLithiumfromGeothermalB(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16944444444444445;

                                final double height = constraints.maxHeight *
                                    0.019853709508881923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3111111111111111,
                                      y: constraints.maxHeight *
                                          0.3124346917450366,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated45magoWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24444444444444444;

                                final double height =
                                    constraints.maxHeight * 0.09195402298850575;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03611111111111111,
                                      y: constraints.maxHeight *
                                          0.34691745036572624,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle261Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6583333333333333;

                                final double height =
                                    constraints.maxHeight * 0.03761755485893417;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3111111111111111,
                                      y: constraints.maxHeight *
                                          0.3605015673981191,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedLivingWallsCanReduceHeatLostfromBuildingsbyOver30Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.12777777777777777;

                                final double height = constraints.maxHeight *
                                    0.019853709508881923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.4117032392894462,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated1hagoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24444444444444444;

                                final double height =
                                    constraints.maxHeight * 0.09195402298850575;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.4555903866248694,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle262Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6583333333333333;

                                final double height =
                                    constraints.maxHeight * 0.03761755485893417;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.46917450365726227,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedHealthierUKDietsLinkedtoLowerGreenhouseGasEmissionsWidg(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.13333333333333333;

                                final double height = constraints.maxHeight *
                                    0.019853709508881923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.5214211076280042,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated2hagoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24444444444444444;

                                final double height =
                                    constraints.maxHeight * 0.09195402298850575;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.5642633228840125,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle263Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6583333333333333;

                                final double height =
                                    constraints.maxHeight * 0.03761755485893417;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.5778474399164054,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedFreeGreenServicesCouldSubstantiallyReduceEmissionsWidge(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.13333333333333333;

                                final double height = constraints.maxHeight *
                                    0.019853709508881923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.625914315569488,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated4hagoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.13333333333333333;

                                final double height = constraints.maxHeight *
                                    0.019853709508881923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.7293625914315569,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated8hagoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24444444444444444;

                                final double height =
                                    constraints.maxHeight * 0.09195402298850575;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.6729362591431557,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle264Widget5(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6583333333333333;

                                final double height =
                                    constraints.maxHeight * 0.03761755485893417;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.6865203761755486,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedHowSugarLovingMicrobesCouldHelpPowerFutureCarsWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.12777777777777777;

                                final double height = constraints.maxHeight *
                                    0.019853709508881923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.31666666666666665,
                                      y: constraints.maxHeight *
                                          0.8526645768025078,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated1dagoWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24444444444444444;

                                final double height =
                                    constraints.maxHeight * 0.09195402298850575;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03611111111111111,
                                      y: constraints.maxHeight *
                                          0.7816091954022989,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle265Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6583333333333333;

                                final double height =
                                    constraints.maxHeight * 0.07314524555903866;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3111111111111111,
                                      y: constraints.maxHeight *
                                          0.7816091954022989,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedStudyConfirmsThatGabonIstheLargestStrongholdforCritical(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.13333333333333333;

                                final double height = constraints.maxHeight *
                                    0.019853709508881923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3111111111111111,
                                      y: constraints.maxHeight *
                                          0.9467084639498433,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated2dagoWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24444444444444444;

                                final double height =
                                    constraints.maxHeight * 0.09195402298850575;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03611111111111111,
                                      y: constraints.maxHeight *
                                          0.890282131661442,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle266Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6583333333333333;

                                final double height =
                                    constraints.maxHeight * 0.03761755485893417;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3111111111111111,
                                      y: constraints.maxHeight *
                                          0.9038662486938349,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedShapingaSustainableFutureforaCommonPlasticWidget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
