import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedRectangle244Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedRectangle246Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedVideosWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedRectangle245Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedHowmuchCO2emissionsfromyourfoodWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedRectangle205Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedRectangle202Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedRectangle206Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedContentWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedRectangle204Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedShoppinglistWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedFoodRootsWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedNewsWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedDoyouknow95ofyourfoodisenviromentallyfriendlyWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedArticlesWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedRectangle201Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedActionsettingsWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomescreenwidget/generated/GeneratedRectangle200Widget.dart';

/* Frame Home Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 16.0,
                  top: 123.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 142.0,
                  child: GeneratedRectangle244Widget(),
                ),
                Positioned(
                  left: 127.0,
                  top: 124.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 142.0,
                  child: GeneratedRectangle245Widget(),
                ),
                Positioned(
                  left: 238.0,
                  top: 124.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 142.0,
                  child: GeneratedRectangle246Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.5361111111111111;

                    final double height = constraints.maxHeight * 0.0765625;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.23333333333333334,
                          y: constraints.maxHeight * 0.009375,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle206Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 84.0,
                  top: 6.0,
                  right: null,
                  bottom: null,
                  width: 198.0,
                  height: 54.0,
                  child: GeneratedFoodRootsWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.13020833333333334;

                    final double height = constraints.maxHeight * 0.0703125;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.8555555555555555,
                          y: constraints.maxHeight * 0.009375,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedActionsettingsWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.9222222222222223;

                    final double height = constraints.maxHeight * 0.134375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.03888888888888889,
                          y: constraints.maxHeight * 0.7171875,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle200Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.4861111111111111;

                    final double height = constraints.maxHeight * 0.134375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.03888888888888889,
                          y: constraints.maxHeight * 0.4640625,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle201Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.26666666666666666;

                    final double height = constraints.maxHeight * 0.134375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.06388888888888888,
                          y: constraints.maxHeight * 0.2140625,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle202Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.26666666666666666;

                    final double height = constraints.maxHeight * 0.134375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.36944444444444446,
                          y: constraints.maxHeight * 0.2140625,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle204Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width = constraints.maxWidth * 0.25;

                    final double height = constraints.maxHeight * 0.134375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.6888888888888889,
                          y: constraints.maxHeight * 0.2140625,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle205Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.40555555555555556;

                    final double height = constraints.maxHeight * 0.0609375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: 0,
                          y: constraints.maxHeight * 0.3609375,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedVideosWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.3194444444444444;

                    final double height = constraints.maxHeight * 0.0609375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.3527777777777778,
                          y: constraints.maxHeight * 0.3609375,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedArticlesWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.3194444444444444;

                    final double height = constraints.maxHeight * 0.0609375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.6611111111111111,
                          y: constraints.maxHeight * 0.3609375,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedNewsWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.3972222222222222;

                    final double height = constraints.maxHeight * 0.1234375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.5527777777777778,
                          y: constraints.maxHeight * 0.471875,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child:
                                GeneratedDoyouknow95ofyourfoodisenviromentallyfriendlyWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 28.0,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 301.0,
                  height: 79.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 109.50,
                      z: 0,
                      child: GeneratedHowmuchCO2emissionsfromyourfoodWidget()),
                ),
                Positioned(
                  left: null,
                  top: 3.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: TransformHelper.translate(
                      x: -155.00,
                      y: 0.00,
                      z: 0,
                      child: GeneratedEllipse7Widget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 334.0,
                  height: 36.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -232.00,
                      z: 0,
                      child: GeneratedContentWidget()),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.08888888888888889;

                    final double height = constraints.maxHeight * 0.0484375;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.8555555555555555,
                          y: constraints.maxHeight * 0.1140625,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedImage3Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.17222222222222222;

                    final double height = constraints.maxHeight * 0.025;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.03888888888888889,
                          y: constraints.maxHeight * 0.0703125,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedShoppinglistWidget1(),
                          ))
                    ]);
                  }),
                )
              ]),
        ),
      ),
    ));
  }
}
