import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedsupplychainwidget/generated/GeneratedSuplyWidget1.dart';

/* Frame Supply chain
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSupplychainWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 758.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 412.0,
                      height: 758.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 11.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 729.0,
                              child: GeneratedSuplyWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
