import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget/generated/GeneratedSearchscrollWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget/generated/GeneratedLargeFABWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget/generated/GeneratedDeviceDeviceframecomponentsWidget17.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget/generated/GeneratedSearchBarWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget/generated/GeneratedNavigationbarWidget8.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget/generated/GeneratedDeviceDeviceframecomponentsWidget16.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget/generated/GeneratedTopappbarWidget8.dart';

/* Frame Search Input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchInputWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 636.0,
                child: GeneratedSearchscrollWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget8(),
              ),
              Positioned(
                left: 12.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 45.0,
                child: GeneratedSearchBarWidget1(),
              ),
              Positioned(
                left: -4.547473508864641e-13,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget17(),
              ),
              Positioned(
                left: 300.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedLargeFABWidget1(),
              )
            ]),
      ),
    ));
  }
}
