import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedStackedcardWidget38.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedSearchBarWidget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedButtonWidget97.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedDeviceDeviceframecomponentsWidget27.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedButtonWidget96.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedDeviceDeviceframecomponentsWidget26.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedNavigationbarWidget12.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedTopappbarWidget12.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedButtonWidget95.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomewidget25/generated/GeneratedStackedcardWidget37.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget25 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget26(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget27(),
              ),
              Positioned(
                left: 9.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 46.0,
                child: GeneratedSearchBarWidget3(),
              ),
              Positioned(
                left: 64.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 40.0,
                child: GeneratedButtonWidget95(),
              ),
              Positioned(
                left: 161.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 40.0,
                child: GeneratedButtonWidget96(),
              ),
              Positioned(
                left: 264.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 40.0,
                child: GeneratedButtonWidget97(),
              ),
              Positioned(
                left: 27.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 262.0,
                child: GeneratedStackedcardWidget37(),
              ),
              Positioned(
                left: 27.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 239.0,
                child: GeneratedStackedcardWidget38(),
              )
            ]),
      ),
    ));
  }
}
