import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomenewswidget/generated/GeneratedButtonWidget113.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomenewswidget/generated/GeneratedFrame2608136Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomenewswidget/generated/GeneratedNavigationbarWidget14.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomenewswidget/generated/GeneratedButtonWidget112.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomenewswidget/generated/GeneratedDeviceDeviceframecomponentsWidget30.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomenewswidget/generated/GeneratedDeviceDeviceframecomponentsWidget31.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomenewswidget/generated/GeneratedSearchBarWidget5.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomenewswidget/generated/GeneratedTopappbarWidget14.dart';
import 'package:flutterapp/food_20rootsapp/generatedhomenewswidget/generated/GeneratedButtonWidget111.dart';

/* Frame Home News
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeNewsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget30(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget31(),
              ),
              Positioned(
                left: 9.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 46.0,
                child: GeneratedSearchBarWidget5(),
              ),
              Positioned(
                left: 64.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 40.0,
                child: GeneratedButtonWidget111(),
              ),
              Positioned(
                left: 161.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 40.0,
                child: GeneratedButtonWidget112(),
              ),
              Positioned(
                left: 264.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 40.0,
                child: GeneratedButtonWidget113(),
              ),
              Positioned(
                left: 0.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 566.0,
                child: GeneratedFrame2608136Widget(),
              )
            ]),
      ),
    ));
  }
}
