import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedLine25Widget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedDeviceDeviceframecomponentsWidget40.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedMenuWidget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedHeadWidget2.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedItemWidget37.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedLargeFABWidget4.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedItemWidget36.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedDeviceDeviceframecomponentsWidget41.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedItemWidget35.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedNavigationbarWidget19.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedItemWidget34.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedLine24Widget36.dart';
import 'package:flutterapp/food_20rootsapp/generatedproductstoreswidget/generated/GeneratedTopappbarWidget19.dart';

/* Frame Product Stores
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProductStoresWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget40(),
              ),
              Positioned(
                left: 46.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedMenuWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget41(),
              ),
              Positioned(
                left: 0.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 414.0193786621094,
                height: 137.0,
                child: GeneratedHeadWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 414.0193176269531,
                height: 0.5,
                child: GeneratedLine24Widget36(),
              ),
              Positioned(
                left: -6.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 419.0,
                height: 90.0,
                child: GeneratedItemWidget34(),
              ),
              Positioned(
                left: -3.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 414.0000305175781,
                height: 90.0,
                child: GeneratedItemWidget35(),
              ),
              Positioned(
                left: -4.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 414.0193176269531,
                height: 0.5,
                child: GeneratedLine25Widget3(),
              ),
              Positioned(
                left: -7.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 422.0,
                height: 90.0,
                child: GeneratedItemWidget36(),
              ),
              Positioned(
                left: -6.0,
                top: 627.0,
                right: null,
                bottom: null,
                width: 422.0,
                height: 90.0,
                child: GeneratedItemWidget37(),
              ),
              Positioned(
                left: 300.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedLargeFABWidget4(),
              )
            ]),
      ),
    ));
  }
}
