import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedproducthealthwidget/generated/GeneratedLargeFABWidget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedproducthealthwidget/generated/GeneratedDeviceDeviceframecomponentsWidget39.dart';
import 'package:flutterapp/food_20rootsapp/generatedproducthealthwidget/generated/GeneratedDeviceDeviceframecomponentsWidget38.dart';
import 'package:flutterapp/food_20rootsapp/generatedproducthealthwidget/generated/GeneratedNavigationbarWidget18.dart';
import 'package:flutterapp/food_20rootsapp/generatedproducthealthwidget/generated/GeneratedLine24Widget35.dart';
import 'package:flutterapp/food_20rootsapp/generatedproducthealthwidget/generated/GeneratedMenuWidget2.dart';
import 'package:flutterapp/food_20rootsapp/generatedproducthealthwidget/generated/GeneratedTopappbarWidget18.dart';
import 'package:flutterapp/food_20rootsapp/generatedproducthealthwidget/generated/GeneratedHeadWidget1.dart';

/* Frame Product Health
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProductHealthWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 86.0,
                child: GeneratedNavigationbarWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget38(),
              ),
              Positioned(
                left: 46.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedMenuWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 64.0,
                child: GeneratedTopappbarWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget39(),
              ),
              Positioned(
                left: 0.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 414.0193786621094,
                height: 137.0,
                child: GeneratedHeadWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 414.0193176269531,
                height: 0.5,
                child: GeneratedLine24Widget35(),
              ),
              Positioned(
                left: 300.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedLargeFABWidget3(),
              )
            ]),
      ),
    ));
  }
}
