import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchscrollwidget1/generated/GeneratedGroup21Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchscrollwidget1/generated/GeneratedRectangle282Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchscrollwidget1/generated/GeneratedGroup20Widget1.dart';

/* Frame Search scroll
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchscrollWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 819.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 412.0,
                      height: 819.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 412.0,
                              height: 819.0,
                              child: GeneratedRectangle282Widget1(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 402.218505859375,
                              height: 810.0,
                              child: GeneratedGroup20Widget1(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 402.218505859375,
                              height: 810.0,
                              child: GeneratedGroup21Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
