import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup10widget/generated/GeneratedRectangle269Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup10widget/generated/GeneratedRectangle276Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup10widget/generated/GeneratedImage4Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup10widget/generated/GeneratedRectangle267Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup10widget/generated/GeneratedImage5Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedgroup10widget/generated/GeneratedRectangle268Widget2.dart';

/* Group Group 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 903.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 2180.0,
                    height: 903.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 2180.0,
                            height: 903.0,
                            child: GeneratedRectangle276Widget(),
                          ),
                          Positioned(
                            left: 47.0,
                            top: 78.0,
                            right: null,
                            bottom: null,
                            width: 413.0,
                            height: 137.0,
                            child: GeneratedRectangle267Widget1(),
                          ),
                          Positioned(
                            left: 569.0,
                            top: 78.0,
                            right: null,
                            bottom: null,
                            width: 412.0,
                            height: 112.0,
                            child: GeneratedRectangle268Widget2(),
                          ),
                          Positioned(
                            left: 1061.0,
                            top: 78.0,
                            right: null,
                            bottom: null,
                            width: 402.0,
                            height: 155.0,
                            child: GeneratedRectangle269Widget1(),
                          ),
                          Positioned(
                            left: 173.0,
                            top: 350.0,
                            right: null,
                            bottom: null,
                            width: 1290.0,
                            height: 478.0,
                            child: GeneratedImage5Widget1(),
                          ),
                          Positioned(
                            left: 1506.0,
                            top: 55.0,
                            right: null,
                            bottom: null,
                            width: 535.0,
                            height: 270.0,
                            child: GeneratedImage4Widget1(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
