import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedTheEcologyofUnpredictabilityWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedRectangle258Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/Generated2dagoWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedWaterisWealthWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedTheTroublewithConsumptionWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedRectangle247Widget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/Generated30magoWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedInHonoluluenvironmentalactivistsareseekingtoremaketheir.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedFoodscarbonfootprintorfoodprintisthegreenhousegasemissi.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedWhatdoesthedisappearanceofoncepopularorubiquitousobject.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/Generated8magoWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedRectangle250Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedRectangle252Widget3.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedThecontradictionsbetweencapitalistprioritiesandecologic.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/Generated1dagoWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedRectangle254Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedHowmuchCO2emissionsfromyourfoodWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedThreeThinkinWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/Generated45magoWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticlesscrollwidget/generated/GeneratedBirchtreesclumpedinthicketsareusuallyfoundatderelictand.dart';

/* Frame Articles Scroll
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArticlesScrollWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1652.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1652.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9305555555555556;

                                final double height =
                                    constraints.maxHeight * 0.11259079903147699;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.400726392251816,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle247Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height = constraints.maxHeight *
                                    0.011501210653753027;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.32263922518159804,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedHowmuchCO2emissionsfromyourfoodWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0423728813559322;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.3383777239709443,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedFoodscarbonfootprintorfoodprintisthegreenhousegasemissi(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16944444444444445;

                                final double height = constraints.maxHeight *
                                    0.011501210653753027;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.3837772397094431,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated30magoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9305555555555556;

                                final double height =
                                    constraints.maxHeight * 0.11259079903147699;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03888888888888889,
                                      y: constraints.maxHeight *
                                          0.00847457627118644,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle250Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height = constraints.maxHeight *
                                    0.012711864406779662;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.12530266343825666,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedWaterisWealthWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0423728813559322;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.1410411622276029,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedInHonoluluenvironmentalactivistsareseekingtoremaketheir(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.14444444444444443;

                                final double height = constraints.maxHeight *
                                    0.011501210653753027;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.1864406779661017,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated8magoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9305555555555556;

                                final double height =
                                    constraints.maxHeight * 0.11259079903147699;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.044444444444444446,
                                      y: constraints.maxHeight *
                                          0.7953995157384988,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle258Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height = constraints.maxHeight *
                                    0.012711864406779662;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.04722222222222222,
                                      y: constraints.maxHeight *
                                          0.912227602905569,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedTheTroublewithConsumptionWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0526634382566586;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.04722222222222222,
                                      y: constraints.maxHeight *
                                          0.9279661016949152,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedThecontradictionsbetweencapitalistprioritiesandecologic(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.13333333333333333;

                                final double height = constraints.maxHeight *
                                    0.011501210653753027;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.04722222222222222,
                                      y: constraints.maxHeight *
                                          0.9836561743341404,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated2dagoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9305555555555556;

                                final double height =
                                    constraints.maxHeight * 0.11259079903147699;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.044444444444444446,
                                      y: constraints.maxHeight *
                                          0.5980629539951574,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle252Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height = constraints.maxHeight *
                                    0.012711864406779662;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.04722222222222222,
                                      y: constraints.maxHeight *
                                          0.7148910411622276,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedTheEcologyofUnpredictabilityWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0423728813559322;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.04722222222222222,
                                      y: constraints.maxHeight *
                                          0.7306295399515739,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedBirchtreesclumpedinthicketsareusuallyfoundatderelictand(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.12777777777777777;

                                final double height = constraints.maxHeight *
                                    0.011501210653753027;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.04722222222222222,
                                      y: constraints.maxHeight *
                                          0.7760290556900726,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated1dagoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height = constraints.maxHeight *
                                    0.012711864406779662;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.044444444444444446,
                                      y: constraints.maxHeight *
                                          0.5199757869249395,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedThreeThinkinWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9333333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0423728813559322;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.044444444444444446,
                                      y: constraints.maxHeight *
                                          0.5357142857142857,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedWhatdoesthedisappearanceofoncepopularorubiquitousobject(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16944444444444445;

                                final double height = constraints.maxHeight *
                                    0.011501210653753027;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.041666666666666664,
                                      y: constraints.maxHeight *
                                          0.5811138014527845,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated45magoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9305555555555556;

                                final double height =
                                    constraints.maxHeight * 0.11259079903147699;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03888888888888889,
                                      y: constraints.maxHeight *
                                          0.2033898305084746,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle254Widget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
