import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/GeneratedArticlesWidget2.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/Generated14spBody1RegularWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/GeneratedArticlesScrollWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/GeneratedSearchWidget32.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/GeneratedMenuWidget4.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/GeneratedFILTERWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/GeneratedVectorWidget170.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/GeneratedMenuWidget5.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/GeneratedDropdownWidget.dart';
import 'package:flutterapp/food_20rootsapp/generatedarticleswidget1/generated/GeneratedToggleWidget.dart';

/* Frame Articles
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArticlesWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08888888888888889;
                  double scaleX = (constraints.maxWidth * percentWidth) / 32.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.027777777777777776,
                        translateY: constraints.maxHeight * 0.028125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget170())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.28888888888888886;

                  final double height = constraints.maxHeight * 0.0609375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3611111111111111,
                        y: constraints.maxHeight * 0.021875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedArticlesWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.15833333333333333;

                  final double height = constraints.maxHeight * 0.0375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8222222222222222,
                        y: constraints.maxHeight * 0.09375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFILTERWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.21388888888888888;

                  final double height = constraints.maxHeight * 0.0375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.03888888888888889,
                        y: constraints.maxHeight * 0.09375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated14spBody1RegularWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06666666666666667;

                  final double height = constraints.maxHeight * 0.0375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2388888888888889,
                        y: constraints.maxHeight * 0.09375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDropdownWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.26666666666666666;

                  final double height = constraints.maxHeight * 0.05;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.4111111111111111,
                        y: constraints.maxHeight * 0.0875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToggleWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1111111111111111;

                  final double height = constraints.maxHeight * 0.0625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8666666666666667,
                        y: constraints.maxHeight * 0.0171875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSearchWidget32(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight * 0.128125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.871875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight * 0.734375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.1375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedArticlesScrollWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight * 0.128125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.871875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuWidget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
