import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailsscrollwidget/generated/GeneratedStackedcardWidget62.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailsscrollwidget/generated/GeneratedItemWidget54.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailsscrollwidget/generated/GeneratedPreparationWidget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailsscrollwidget/generated/GeneratedItemWidget55.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailsscrollwidget/generated/GeneratedMakealemonchickenmarinadeWellitsreallymorelikearuborapa1.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailsscrollwidget/generated/GeneratedRectangle284Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedrecipedetailsscrollwidget/generated/GeneratedItemWidget56.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Recipe details scroll
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRecipedetailsscrollWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 412.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 521.0,
                              right: null,
                              bottom: null,
                              width: 412.0,
                              height: 503.0,
                              child: GeneratedRectangle284Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.8956310679611651;

                                final double height =
                                    constraints.maxHeight * 0.458984375;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.04611650485436893,
                                      y: constraints.maxHeight * 0.5302734375,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedMakealemonchickenmarinadeWellitsreallymorelikearuborapa1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 232.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 92.0,
                              child: GeneratedItemWidget54(),
                            ),
                            Positioned(
                              left: -2.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 92.0,
                              child: GeneratedItemWidget55(),
                            ),
                            Positioned(
                              left: -2.0,
                              top: 414.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 92.0,
                              child: GeneratedItemWidget56(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.8033980582524272;

                                final double height =
                                    constraints.maxHeight * 0.0322265625;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.08495145631067962,
                                      y: constraints.maxHeight * 0.5087890625,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedPreparationWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 422.0,
                              height: 232.0,
                              child: GeneratedStackedcardWidget62(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
