import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget1/generated/GeneratedRectangle270Widget.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget1/generated/GeneratedDeviceDeviceframecomponentsWidget19.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget1/generated/GeneratedDeviceDeviceframecomponentsWidget18.dart';
import 'package:flutterapp/food_20rootsapp/generatedsearchinputwidget1/generated/GeneratedImage18Widget.dart';

/* Frame Search Input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchInputWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(18.0),
      child: Container(
        width: 412.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(127, 116, 119, 117),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(18.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 902.0,
                child: GeneratedImage18Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 28.0,
                child: GeneratedDeviceDeviceframecomponentsWidget18(),
              ),
              Positioned(
                left: -4.547473508864641e-13,
                top: -10.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 52.0,
                child: GeneratedDeviceDeviceframecomponentsWidget19(),
              ),
              Positioned(
                left: 65.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 222.0,
                child: GeneratedRectangle270Widget(),
              )
            ]),
      ),
    ));
  }
}
