import 'package:flutter/material.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget3/generated/GeneratedGroup15Widget1.dart';
import 'package:flutterapp/food_20rootsapp/generatedvideosscrollwidget3/generated/GeneratedRectangle281Widget1.dart';

/* Frame Videos scroll
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVideosscrollWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 847.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 412.0,
                      height: 847.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 412.0,
                              height: 847.0,
                              child: GeneratedRectangle281Widget1(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 12.0,
                              right: null,
                              bottom: null,
                              width: 384.0,
                              height: 817.0,
                              child: GeneratedGroup15Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
